#!/bin/bash

readargs() {
  while [ "$#" -gt 0 ] ; do
    case "$1" in
       -c)
        if [ "$2" ] ; then
          branch="$2"
          shift ; shift
        else
          echo "Missing a value for $1."
          echo
          shift
          usage
exit
        fi
      ;;
      *)
        echo "Unknown option or argument $1."
        echo
        shift
        usage
      exit
      ;;
    esac
  done
}

#  BEGIN THE PROGRAM
readargs "$@"
name=brave

rm -rf ${name}-browser-${branch}/
rm -f ${name}-browser-${branch}.tar.gz
git clone -b ${branch} https://github.com/brave/brave-browser.git ${name}-browser-${branch} 
pushd ${name}-browser-${branch}
git submodule update --init --recursive
echo "You are in Commit: $( git rev-parse HEAD )"
popd
tar -cvzf ${name}-browser-${branch}.tar.gz ${name}-browser-${branch}

